#+TITLE: My Aerospace Config
#+AUTHOR: John Szaniszlo

* Default Settings Reference

#+BEGIN_SRC toml
  # 'main' binding mode declaration
  # See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
  # 'main' binding mode must be always presented
  # Fallback value (if you omit the key): mode.main.binding = {}
  [mode.main.binding]
      # See: https://nikitabobko.github.io/AeroSpace/commands#layout
      alt-slash = 'layout tiles horizontal vertical'
      alt-comma = 'layout accordion horizontal vertical'

      # See: https://nikitabobko.github.io/AeroSpace/commands#focus
      alt-h = 'focus left'
      alt-j = 'focus down'
      alt-k = 'focus up'
      alt-l = 'focus right'

      # See: https://nikitabobko.github.io/AeroSpace/commands#move
      alt-shift-h = 'move left'
      alt-shift-j = 'move down'
      alt-shift-k = 'move up'
      alt-shift-l = 'move right'

      # See: https://nikitabobko.github.io/AeroSpace/commands#resize
      alt-minus = 'resize smart -50'
      alt-equal = 'resize smart +50'

      # See: https://nikitabobko.github.io/AeroSpace/commands#workspace
      alt-1 = 'workspace 1'
      alt-2 = 'workspace 2'
      alt-3 = 'workspace 3'
      alt-4 = 'workspace 4'
      alt-5 = 'workspace 5'
      alt-6 = 'workspace 6'
      alt-7 = 'workspace 7'
      alt-8 = 'workspace 8'
      alt-9 = 'workspace 9'
      alt-a = 'workspace A' # In your config, you can drop workspace bindings that you don't need
      alt-b = 'workspace B'
      alt-c = 'workspace C'
      alt-d = 'workspace D'
      alt-e = 'workspace E'
      alt-f = 'workspace F'
      alt-g = 'workspace G'
      alt-i = 'workspace I'
      alt-m = 'workspace M'
      alt-n = 'workspace N'
      alt-o = 'workspace O'
      alt-p = 'workspace P'
      alt-q = 'workspace Q'
      alt-r = 'workspace R'
      alt-s = 'workspace S'
      alt-t = 'workspace T'
      alt-u = 'workspace U'
      alt-v = 'workspace V'
      alt-w = 'workspace W'
      alt-x = 'workspace X'
      alt-y = 'workspace Y'
      alt-z = 'workspace Z'

      # See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
      alt-shift-1 = 'move-node-to-workspace 1'
      alt-shift-2 = 'move-node-to-workspace 2'
      alt-shift-3 = 'move-node-to-workspace 3'
      alt-shift-4 = 'move-node-to-workspace 4'
      alt-shift-5 = 'move-node-to-workspace 5'
      alt-shift-6 = 'move-node-to-workspace 6'
      alt-shift-7 = 'move-node-to-workspace 7'
      alt-shift-8 = 'move-node-to-workspace 8'
      alt-shift-9 = 'move-node-to-workspace 9'
      alt-shift-a = 'move-node-to-workspace A'
      alt-shift-b = 'move-node-to-workspace B'
      alt-shift-c = 'move-node-to-workspace C'
      alt-shift-d = 'move-node-to-workspace D'
      alt-shift-e = 'move-node-to-workspace E'
      alt-shift-f = 'move-node-to-workspace F'
      alt-shift-g = 'move-node-to-workspace G'
      alt-shift-i = 'move-node-to-workspace I'
      alt-shift-m = 'move-node-to-workspace M'
      alt-shift-n = 'move-node-to-workspace N'
      alt-shift-o = 'move-node-to-workspace O'
      alt-shift-p = 'move-node-to-workspace P'
      alt-shift-q = 'move-node-to-workspace Q'
      alt-shift-r = 'move-node-to-workspace R'
      alt-shift-s = 'move-node-to-workspace S'
      alt-shift-t = 'move-node-to-workspace T'
      alt-shift-u = 'move-node-to-workspace U'
      alt-shift-v = 'move-node-to-workspace V'
      alt-shift-w = 'move-node-to-workspace W'
      alt-shift-x = 'move-node-to-workspace X'
      alt-shift-y = 'move-node-to-workspace Y'
      alt-shift-z = 'move-node-to-workspace Z'

      # See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
      alt-tab = 'workspace-back-and-forth'
      # See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
      alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

      # See: https://nikitabobko.github.io/AeroSpace/commands#mode
      alt-shift-semicolon = 'mode service'

  # 'service' binding mode declaration.
  # See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
  [mode.service.binding]
      esc = ['reload-config', 'mode main']
      r = ['flatten-workspace-tree', 'mode main'] # reset layout
      f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
      backspace = ['close-all-windows-but-current', 'mode main']

      # sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
      #s = ['layout sticky tiling', 'mode main']

      alt-shift-h = ['join-with left', 'mode main']
      alt-shift-j = ['join-with down', 'mode main']
      alt-shift-k = ['join-with up', 'mode main']
      alt-shift-l = ['join-with right', 'mode main']

      down = 'volume down'
      up = 'volume up'
      shift-down = ['volume set 0', 'mode main']
#+END_SRC

* Setup
** Startup related settings

Startup [[https://nikitabobko.github.io/AeroSpace/commands][commands]] can be added to the list.

#+BEGIN_SRC toml :tangle aerospace.toml
  after-startup-command = []
  start-at-login = false
#+END_SRC
* [[https://nikitabobko.github.io/AeroSpace/guide#layouts][Layout]] and Behavior
** Window normalization

Enables [[https://nikitabobko.github.io/AeroSpace/guide#normalization][Window Normalization]] to keep the layout optimized.

#+BEGIN_SRC toml :tangle aerospace.toml
  enable-normalization-flatten-containers = true
  enable-normalization-opposite-orientation-for-nested-containers = true
#+END_SRC

** Setting good behaviors

Default root container layout, this will use tiling by default.

#+BEGIN_SRC toml :tangle aerospace.toml
  default-root-container-layout = 'tiles'
#+END_SRC

** Monitor related behaviors

Depending on horizonal or vertical monitor dynamically change root container to be h_tile or v_tile.

#+BEGIN_SRC toml :tangle aerospace.toml
  default-root-container-orientation = 'auto'
#+END_SRC

Move mouse to center of focused creen.

#+BEGIN_SRC toml :tangle aerospace.toml
  on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
#+END_SRC

Disable ~CMD+H~ binding on MacOS.

#+BEGIN_SRC toml :tangle aerospace.toml
  automatically-unhide-macos-hidden-apps = false
#+END_SRC

* Look and Feel
** Padding

Accordion layout padding.  See [[$https://nikitabobko.github.io/AeroSpace/guide#layouts][Layouts]].

#+BEGIN_SRC toml :tangle aerospace.toml
  accordion-padding = 30
#+END_SRC

** Gaps

This sets the gaps between windows (inner) and the monitor edges (outer)

#+BEGIN_SRC toml :tangle aerospace.toml
  [gaps]
      inner.horizontal = 5
      inner.vertical =   5
      outer.left =       5
      outer.bottom =     5
      outer.top =        5
      outer.right =      5
#+END_SRC

* Bindings
** Keyboard Layout

Sets the layout to use ~qwerty~

#+BEGIN_SRC toml :tangle aerospace.toml
  [key-mapping]
  preset = 'qwerty'
#+END_SRC

** Main bind mode

Begin the declaration for bindings in the main mode.  See [[https://nikitabobko.github.io/AeroSpace/guide#binding-modes][Binding Modes]].

#+BEGIN_SRC toml :tangle aerospace.toml
  [mode.main.binding]
#+END_SRC

*** Change between ~tiles~ and ~acordion~ layouts.

See [[https://nikitabobko.github.io/AeroSpace/commands#layout][Layouts]].

#+BEGIN_SRC toml :tangle aerospace.toml
      alt-slash = 'layout tiles horizontal vertical'
      alt-comma = 'layout accordion horizontal vertical'
#+END_SRC

*** Focus between windows

See [[https://nikitabobko.github.io/AeroSpace/commands#focus][Focus]].

#+BEGIN_SRC toml :tangle aerospace.toml
      alt-h = 'focus left'
      alt-j = 'focus down'
      alt-k = 'focus up'
      alt-l = 'focus right'
#+END_SRC

*** Move windows around

See [[https://nikitabobko.github.io/AeroSpace/commands#move][Move]].

#+BEGIN_SRC toml :tangle aerospace.toml
  alt-shift-h = 'move left'
  alt-shift-j = 'move down'
  alt-shift-k = 'move up'
  alt-shift-l = 'move right'
#+END_SRC

*** Resize windows

See [[https://nikitabobko.github.io/AeroSpace/commands#resize][Resize]].

#+BEGIN_SRC toml :tangle aerospace.toml
  alt-minus = 'resize smart -50'
  alt-equal = 'resize smart +50'
#+END_SRC

*** Move between workspaces

See [[https://nikitabobko.github.io/AeroSpace/commands#workspace][Workspace]].

#+BEGIN_SRC toml :tangle aerospace.toml
  alt-1 = 'workspace 1'
  alt-2 = 'workspace 2'
  alt-3 = 'workspace 3'
  alt-4 = 'workspace 4'
  alt-5 = 'workspace 5'
  alt-6 = 'worksapce 6'
#+END_SRC

*** Move windows/nodes between workspaces

See [[https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace][Move Node to Workspace]].

#+BEGIN_SRC toml :tangle aerospace.toml
  alt-shift-1 = 'move-node-to-workspace 1'
  alt-shift-2 = 'move-node-to-workspace 2'
  alt-shift-3 = 'move-node-to-workspace 3'
  alt-shift-4 = 'move-node-to-workspace 4'
  alt-shift-5 = 'move-node-to-workspace 5'
  alt-shift-6 = 'move-node-to-workspace 6'
#+END_SRC

*** Misc Bindings

#+BEGIN_SRC toml :tangle aerospace.toml
  alt-tab = 'workspace-back-and-forth'
  alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'
  alt-shift-semicolon = 'mode service'
#+END_SRC

** Service bind mode

Begin the declaration for bindings in the service mode.

#+BEGIN_SRC toml :tangle aerospace.toml
    [mode.service.binding]
#+END_SRC

*** Utility binds

#+BEGIN_SRC toml :tangle aerospace.toml

  esc = ['reload-config', 'mode main']
  r = ['flatten-workspace-tree', 'mode main'] # reset layout
  f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
  backspace = ['close-all-windows-but-current', 'mode main']
#+END_SRC

*** Joining Windows

This moves windows into the layout which you are joing into.

#+BEGIN_SRC toml :tangle aerospace.toml
  alt-shift-h = ['join-with left', 'mode main']
  alt-shift-j = ['join-with down', 'mode main']
  alt-shift-k = ['join-with up', 'mode main']
  alt-shift-l = ['join-with right', 'mode main']
#+END_SRC

* tangle aerospace on save
;; Local Variables:
;; eval: (add-hook 'after-save-hook (lambda () (org-babel-tangle)) nil 'make-it-local)
;; End:
