#+TITLE: My Aerospace Config
#+AUTHOR: John Szaniszlo

* Setup
** Startup related settings

Startup [[https://nikitabobko.github.io/AeroSpace/commands][commands]] can be added to the list.

#+BEGIN_SRC toml :tangle aerospace.toml
  after-startup-command = []
  start-at-login = true
#+END_SRC
* [[https://nikitabobko.github.io/AeroSpace/guide#layouts][Layout]] and Behavior
** Window normalization

Enables [[https://nikitabobko.github.io/AeroSpace/guide#normalization][Window Normalization]] to keep the layout optimized.

#+BEGIN_SRC toml :tangle aerospace.toml
  enable-normalization-flatten-containers = true
  enable-normalization-opposite-orientation-for-nested-containers = true
#+END_SRC

** Setting good behaviors

Default root container layout, this will use tiling by default.

#+BEGIN_SRC toml :tangle aerospace.toml
  default-root-container-layout = 'tiles'
#+END_SRC

** Monitor related behaviors

Depending on horizonal or vertical monitor dynamically change root container to be h_tile or v_tile.

#+BEGIN_SRC toml :tangle aerospace.toml
  default-root-container-orientation = 'auto'
#+END_SRC

Move mouse to center of focused creen.

#+BEGIN_SRC toml :tangle aerospace.toml
  on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
#+END_SRC

Disable ~CMD+H~ binding on MacOS.

#+BEGIN_SRC toml :tangle aerospace.toml
  automatically-unhide-macos-hidden-apps = false
#+END_SRC

* Look and Feel
** Padding

Accordion layout padding.  See [[$https://nikitabobko.github.io/AeroSpace/guide#layouts][Layouts]].

#+BEGIN_SRC toml :tangle aerospace.toml
  accordion-padding = 30
#+END_SRC

** Gaps

This sets the gaps between windows (inner) and the monitor edges (outer)

#+BEGIN_SRC toml :tangle aerospace.toml
  [gaps]
      inner.horizontal = 5
      inner.vertical =   5
      outer.left =       5
      outer.bottom =     5
      outer.top =        5
      outer.right =      5
#+END_SRC

* Bindings
** Keyboard Layout

Sets the layout to use ~qwerty~

#+BEGIN_SRC toml :tangle aerospace.toml
  [key-mapping]
  preset = 'qwerty'
#+END_SRC

** Main bind mode

Begin the declaration for bindings in the main mode.  See [[https://nikitabobko.github.io/AeroSpace/guide#binding-modes][Binding Modes]].

#+BEGIN_SRC toml :tangle aerospace.toml
  [mode.main.binding]
#+END_SRC

*** Change between ~tiles~ and ~acordion~ layouts.

See [[https://nikitabobko.github.io/AeroSpace/commands#layout][Layouts]].

#+BEGIN_SRC toml :tangle aerospace.toml
      alt-slash = 'layout tiles horizontal vertical'
      alt-comma = 'layout accordion horizontal vertical'
#+END_SRC

*** Focus between windows

See [[https://nikitabobko.github.io/AeroSpace/commands#focus][Focus]].

#+BEGIN_SRC toml :tangle aerospace.toml
      alt-h = 'focus left'
      alt-j = 'focus down'
      alt-k = 'focus up'
      alt-l = 'focus right'
#+END_SRC

*** Move windows around

See [[https://nikitabobko.github.io/AeroSpace/commands#move][Move]].

#+BEGIN_SRC toml :tangle aerospace.toml
  alt-shift-h = 'move left'
  alt-shift-j = 'move down'
  alt-shift-k = 'move up'
  alt-shift-l = 'move right'
#+END_SRC

*** Resize windows

See [[https://nikitabobko.github.io/AeroSpace/commands#resize][Resize]].

#+BEGIN_SRC toml :tangle aerospace.toml
  alt-minus = 'resize smart -50'
  alt-equal = 'resize smart +50'
#+END_SRC

*** Move between workspaces

See [[https://nikitabobko.github.io/AeroSpace/commands#workspace][Workspace]].

#+BEGIN_SRC toml :tangle aerospace.toml
  alt-1 = 'workspace 1'
  alt-2 = 'workspace 2'
  alt-3 = 'workspace 3'
  alt-4 = 'workspace 4'
  alt-5 = 'workspace 5'
  alt-6 = 'workspace 6'
#+END_SRC

*** Move windows/nodes between workspaces

See [[https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace][Move Node to Workspace]].

#+BEGIN_SRC toml :tangle aerospace.toml
  alt-shift-1 = 'move-node-to-workspace 1'
  alt-shift-2 = 'move-node-to-workspace 2'
  alt-shift-3 = 'move-node-to-workspace 3'
  alt-shift-4 = 'move-node-to-workspace 4'
  alt-shift-5 = 'move-node-to-workspace 5'
  alt-shift-6 = 'move-node-to-workspace 6'
#+END_SRC

*** Misc Bindings

#+BEGIN_SRC toml :tangle aerospace.toml
  alt-tab = 'workspace-back-and-forth'
  alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'
  alt-shift-semicolon = 'mode service'
#+END_SRC

** Service bind mode

Begin the declaration for bindings in the service mode.

#+BEGIN_SRC toml :tangle aerospace.toml
    [mode.service.binding]
#+END_SRC

*** Utility binds

#+BEGIN_SRC toml :tangle aerospace.toml

  esc = ['reload-config', 'mode main']
  r = ['flatten-workspace-tree', 'mode main'] # reset layout
  f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
  backspace = ['close-all-windows-but-current', 'mode main']
#+END_SRC

*** Joining Windows

This moves windows into the layout which you are joing into.

#+BEGIN_SRC toml :tangle aerospace.toml
  alt-shift-h = ['join-with left', 'mode main']
  alt-shift-j = ['join-with down', 'mode main']
  alt-shift-k = ['join-with up', 'mode main']
  alt-shift-l = ['join-with right', 'mode main']
#+END_SRC

* tangle aerospace on save
;; Local Variables:
;; eval: (add-hook 'after-save-hook (lambda () (org-babel-tangle)) nil 'make-it-local)
;; End:
