theme="kanagawa"

# disable movement keys in insert mode (cuz we are pro :D)
[keys.insert]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"

# relative number line
[editor]
line-number = "relative"